# Generated by Django 6.0.2 on 2026-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_testimonial_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('admin', 'Admin')], default='member', max_length=10),
        ),
    ]
