# Generated by Django 6.0.2 on 2026-03-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notification_officerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerapplication',
            name='department',
            field=models.CharField(choices=[('tech', 'Technical'), ('marketing', 'Marketing'), ('ops', 'Operations'), ('logistics', 'Logistics'), ('finance', 'Finance')], default='tech', max_length=20),
        ),
    ]
