# Generated by Django 6.0.2 on 2026-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_officerapplication_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerapplication',
            name='department',
            field=models.CharField(choices=[('tech', 'Technical'), ('marketing', 'Marketing & Creatives'), ('logistics_ops', 'Logistics & Operations'), ('finance', 'Finance'), ('relations', 'Relations')], default='tech', max_length=20),
        ),
    ]
