# Generated by Django 6.0.2 on 2026-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_username_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
