# Generated by Django 6.0.2 on 2026-03-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='showcase_screenshots/'),
        ),
    ]
