# Generated by Django 6.0.2 on 2026-03-19 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_showcase_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcase',
            name='screenshot',
        ),
        migrations.CreateModel(
            name='ShowcaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='showcase_screenshots/')),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.showcase')),
            ],
        ),
    ]
