# Generated by Django 6.0.2 on 2026-03-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_showcase_screenshot_showcaseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='showcase_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showcase',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='showcase_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShowcaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.showcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
