# Generated by Django 6.0.2 on 2026-03-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_showcase_likes_showcase_saves_showcasecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.showcasecomment'),
        ),
    ]
