# Generated by Django 6.0.2 on 2026-03-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
