# Generated by Django 6.0.3 on 2026-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('tech', 'Technical'), ('marketing', 'Marketing & Creatives'), ('logistics_ops', 'Logistics & Operations'), ('finance', 'Finance'), ('relations', 'Relations')], max_length=20, null=True),
        ),
    ]
