# Generated by Copilot on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
