# Generated by Django 6.0.3 on 2026-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_merge_0028_user_gender_0028_user_officer_term_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerapplication',
            name='position',
            field=models.CharField(blank=True, choices=[('chief', 'Chief'), ('member', 'Member')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('chief', 'Chief'), ('member', 'Member')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='officerapplication',
            name='department',
            field=models.CharField(choices=[('captain', 'Captain'), ('tech', 'Technical'), ('marketing', 'Marketing & Creatives'), ('logistics_ops', 'Logistics & Operations'), ('finance', 'Finance'), ('relations', 'Relations')], default='tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('captain', 'Captain'), ('tech', 'Technical'), ('marketing', 'Marketing & Creatives'), ('logistics_ops', 'Logistics & Operations'), ('finance', 'Finance'), ('relations', 'Relations')], max_length=20, null=True),
        ),
    ]
