# Generated by Django 6.0.3 on 2026-04-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_officerapplication_position_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='officerapplication',
            name='position',
            field=models.CharField(blank=True, choices=[('captain', 'Captain'), ('secretary', 'Secretary'), ('asst_secretary', 'Assistant Secretary'), ('chief_tech', 'Chief of Technical'), ('cloud_solution', 'Cloud Solution Officer'), ('tech_content', 'Technical Content Officer'), ('buildhers_ambassador', 'BuildHers+ Ambassador'), ('chief_marketing', 'Chief of Marketing & Creatives'), ('graphic_multimedia', 'Graphic Multimedia Officer'), ('social_media', 'Social Media Content Officer'), ('chief_relations', 'Chief of Relations'), ('hr', 'Human Resource Officer'), ('membership', 'Membership Officer'), ('chief_finance', 'Chief of Finance'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('chief_logistics', 'Chief of Logistics & Operations'), ('event_coord', 'Event Coordinator'), ('op_asst', 'Operation Assistant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('captain', 'Captain'), ('secretary', 'Secretary'), ('asst_secretary', 'Assistant Secretary'), ('chief_tech', 'Chief of Technical'), ('cloud_solution', 'Cloud Solution Officer'), ('tech_content', 'Technical Content Officer'), ('buildhers_ambassador', 'BuildHers+ Ambassador'), ('chief_marketing', 'Chief of Marketing & Creatives'), ('graphic_multimedia', 'Graphic Multimedia Officer'), ('social_media', 'Social Media Content Officer'), ('chief_relations', 'Chief of Relations'), ('hr', 'Human Resource Officer'), ('membership', 'Membership Officer'), ('chief_finance', 'Chief of Finance'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('chief_logistics', 'Chief of Logistics & Operations'), ('event_coord', 'Event Coordinator'), ('op_asst', 'Operation Assistant')], max_length=20, null=True),
        ),
    ]
