# Generated by Django 6.0.3 on 2026-04-09 05:43

import re
from django.db import migrations, models


def backfill_spots_capacity(apps, schema_editor):
    Event = apps.get_model('base', 'Event')
    for event in Event.objects.filter(spots_capacity__isnull=True):
        raw = (event.spots_left or '').strip()
        if not raw:
            continue
        match = re.search(r'\d+', raw)
        if not match:
            continue
        event.spots_capacity = int(match.group())
        event.save(update_fields=['spots_capacity'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_officerapplication_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spots_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['user_to', 'status', '-created_at'], name='base_connec_user_to_652ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['user_from', 'status', '-created_at'], name='base_connec_user_fr_e53f16_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['event', '-enrolled_at'], name='base_enroll_event_i_86eea5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', '-enrolled_at'], name='base_enroll_user_id_dca3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'event_type'], name='base_event_date_8c5b13_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='base_notifi_user_id_b05745_idx'),
        ),
        migrations.AddIndex(
            model_name='showcasecomment',
            index=models.Index(fields=['showcase', '-created_at'], name='base_showca_showcas_f1b691_idx'),
        ),
        migrations.AddIndex(
            model_name='showcasecomment',
            index=models.Index(fields=['user', '-created_at'], name='base_showca_user_id_aeffa9_idx'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(condition=models.Q(('user_from', models.F('user_to')), _negated=True), name='connection_no_self_connection'),
        ),
        migrations.RunPython(backfill_spots_capacity, migrations.RunPython.noop),
    ]
