# Generated by Django 6.0.3 on 2026-04-10 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_event_spots_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('event_create', 'Created Event'), ('event_edit', 'Edited Event'), ('event_delete', 'Deleted Event'), ('testimonial_toggle', 'Updated Testimonial'), ('testimonial_delete', 'Deleted Testimonial'), ('application_review', 'Reviewed Application'), ('showcase_toggle', 'Updated Showcase'), ('showcase_delete', 'Deleted Showcase'), ('officer_demote', 'Demoted Officer'), ('role_update', 'Updated User Role')], max_length=40)),
                ('summary', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='base_activi_created_0bb0ac_idx'), models.Index(fields=['actor', '-created_at'], name='base_activi_actor_i_35648a_idx')],
            },
        ),
    ]
